references:
  environment:
    CIRCLECI_CLI_VERSION: 0.1.5546
    GOTESTSUM_VERSION: 0.5.2
    GOFUMPT_VERSION: 0.3.1
    GO_TAGS: ''
    GO_IMAGE: docker.mirror.hashicorp.services/cimg/go:1.19.4
go-machine:
  machine:
    image: ubuntu-2004:2022.10.1
  environment:
    CIRCLECI_CLI_VERSION: 0.1.5546
    GOTESTSUM_VERSION: 0.5.2
    GOFUMPT_VERSION: 0.3.1
    GO_TAGS: ''
    GO_IMAGE: docker.mirror.hashicorp.services/cimg/go:1.19.4
  shell: /usr/bin/env bash -euo pipefail -c
  working_directory: /home/circleci/go/src/github.com/hashicorp/vault
node:
  docker:
    - image: docker.mirror.hashicorp.services/circleci/node:14-browsers
      environment:
        JOBS: 2
  shell: /usr/bin/env bash -euo pipefail -c
  working_directory: /home/circleci/go/src/github.com/hashicorp/vault
python:
  docker:
    - image: docker.mirror.hashicorp.services/python:3-alpine
  shell: /usr/bin/env bash -euo pipefail -c
  working_directory: /home/circleci/go/src/github.com/hashicorp/vault
semgrep:
  docker:
    - image: docker.mirror.hashicorp.services/returntocorp/semgrep:0.113.0
  shell: /bin/sh
  working_directory: /home/circleci/go/src/github.com/hashicorp/vault
docker-env-go-test-remote-docker:
  resource_class: medium
  docker:
    - image: docker.mirror.hashicorp.services/cimg/go:1.19.4
  environment:
    CIRCLECI_CLI_VERSION: 0.1.5546
    GOTESTSUM_VERSION: 0.5.2
    GOFUMPT_VERSION: 0.3.1
    GO_TAGS: ''
    GO_IMAGE: docker.mirror.hashicorp.services/cimg/go:1.19.4
  working_directory: /home/circleci/go/src/github.com/hashicorp/vault
docker-env-go-test:
  resource_class: large
  docker:
    - image: docker.mirror.hashicorp.services/cimg/go:1.19.4
  environment:
    CIRCLECI_CLI_VERSION: 0.1.5546
    GOTESTSUM_VERSION: 0.5.2
    GOFUMPT_VERSION: 0.3.1
    GO_TAGS: ''
    GO_IMAGE: docker.mirror.hashicorp.services/cimg/go:1.19.4
  working_directory: /home/circleci/go/src/github.com/hashicorp/vault
docker-env-go-test-race:
  resource_class: xlarge
  docker:
    - image: docker.mirror.hashicorp.services/cimg/go:1.19.4
  environment:
    CIRCLECI_CLI_VERSION: 0.1.5546
    GOTESTSUM_VERSION: 0.5.2
    GOFUMPT_VERSION: 0.3.1
    GO_TAGS: ''
    GO_IMAGE: docker.mirror.hashicorp.services/cimg/go:1.19.4
  working_directory: /home/circleci/go/src/github.com/hashicorp/vault
